# Generated by Django 5.2.1 on 2025-06-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('operator', 'Оператор ЭВМ'), ('parts_manager', 'Менеджер по деталям'), ('orders_manager', 'Менеджер по заказам'), ('supply_manager', 'Менеджер по поставкам'), ('storekeeper', 'Кладовщик'), ('delivery_manager', 'Начальник службы доставки'), ('driver', 'Водитель службы доставки')], default='operator', max_length=20, verbose_name='Роль'),
        ),
    ]
