# Generated by Django 5.2.1 on 2025-05-30 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerDistributionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='dealer_reports/%Y/%m/%d/', verbose_name='Файл отчета')),
                ('waybills_generated', models.BooleanField(default=False, verbose_name='Накладные сгенерированы')),
            ],
            options={
                'verbose_name': 'Отчет по распределению дилерам',
                'verbose_name_plural': 'Отчеты по распределению дилерам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для рассылки')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to='core.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Дилер',
                'verbose_name_plural': 'Дилеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerStockNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.PositiveIntegerField(default=0, verbose_name='Норма запаса')),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Заполняется дилером при отправке файла', verbose_name='Текущий запас')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_norms', to='dealers.dealer', verbose_name='Дилер')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_norms', to='parts.part', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Норма запаса дилера',
                'verbose_name_plural': 'Нормы запасов дилеров',
                'unique_together': {('dealer', 'part')},
            },
        ),
        migrations.CreateModel(
            name='DealerWaybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('waybill_file', models.FileField(blank=True, null=True, upload_to='dealer_waybills/%Y/%m/%d/', verbose_name='Файл накладной')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='dealers.dealer', verbose_name='Дилер')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='dealers.dealerdistributionreport', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Транспортная накладная для дилера',
                'verbose_name_plural': 'Транспортные накладные для дилеров',
                'ordering': ['-created_at'],
                'unique_together': {('report', 'dealer')},
            },
        ),
    ]
